[project]
name = "domain-grant-efficiency"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inquirerpy>=0.3.4",
    "rich>=15.0.0",
    "typer>=0.25.1",
]

[project.scripts]
mytool = "domain_grant_efficiency.main:app"


